---
  - id: dockfmt
    name: dockfmt
    description: Format Dockerfiles using dockfmt without needing docker or system installation
    entry: dockfmt
    language: python
    types:
      - dockerfile
